### ISSUE TITLE
obaa 是否能够用与监听小程序页面 this.data 的变化

### ISSUE THREAD

**Issue by Jackoder** [Tencent/omi#292]
```js
Page({
  data: {
    a: 1
  },
  onLoad: function (options) {
    obaa(this.data, function (name, value, old) {
      console.log(name + "__" + value + "__" + old)
    })
    this.setData({ a: 2 })
  }
})
```
调用之后控制台输出如下：
```log
a__2__1
VM20590:1 thirdScriptError
Converting circular structure to JSON;at "pages/index/index" page lifeCycleMethod onLoad function
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Object.t [as send] (http://127.0.0.1:40791/appservice/appservice?t=1554365183455:2178:1032)
    at Object.e [as publish] (http://127.0.0.1:40791/appservice/appservice?t=1554365183455:2178:20078)
    at Object.publish (http://127.0.0.1:40791/appservice/__dev__/WAService.js:1:117639)
    at n.data (http://127.0.0.1:40791/appservice/__dev__/WAService.js:1:223564)
    at w (http://127.0.0.1:40791/appservice/__dev__/WAService.js:1:223579)
    at Object.vdSyncBatch (http://127.0.0.1:40791/appservice/__dev__/WAService.js:1:755932)
    at t.flushSendingData (http://127.0.0.1:40791/appservice/__dev__/WAService.js:1:903747)
    at i.value (http://127.0.0.1:40791/appservice/__dev__/WAService.js:1:927450)
    at e.value (http://127.0.0.1:40791/appservice/__dev__/WAService.js:1:908253)
```

**Comment by dntzhang** [comment]
```js 
obaa(this.data, [指定下name], function (name, value, old) {
      console.log(name + "__" + value + "__" + old)
    })
```

**Comment by Jackoder** [comment]
修改后还是包上面的错误，代码如下：

```js
obaa(this.data, ['a'], function (name, value, old) {
  console.log(name + "__" + value + "__" + old)
})
this.setData({ a: 2 })
```

**Comment by dntzhang** [comment]
this.oData.a = 2 啊

**Comment by dntzhang** [comment]
不行。放弃吧~

**Comment by dntzhang** [comment]
omix 进行了一次深拷贝 https://github.com/Tencent/omi/blob/master/packages/omix/utils/create.js#L18

**Comment by Jackoder** [comment]
OK~
